name: Run Translation Script and Post to WordPress

on:
  workflow_dispatch:  # Manual run from Actions tab
  #schedule:
    #- cron: "0 * * * *"  # Uncomment to run every hour

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install google-generativeai requests beautifulsoup4
          pip install --upgrade google-generativeai

      - name: Verify Secrets
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: |
          if [ -z "${APIFY_API_TOKEN}" ] || [ -z "${GEMINI_API_KEY}" ] || [ -z "${WP_USER}" ] || [ -z "${WP_APP_PASSWORD}" ]; then
            echo "❌ One or more secrets are missing!"
            exit 1
          fi

      - name: Run translation and posting script
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_URL: ${{ secrets.WP_URL }}
        run: |
          python cryptonews_translator.py
          echo "[DEBUG] Contents of translated_news.json:"
          cat translated_news.json || echo "[WARNING] translated_news.json not found or empty"

      - name: Commit and push translated news JSON
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add translated_news.json
          git status
          git diff --cached --quiet || git commit -m "Update translated news"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git main
